### ISSUE TITLE
return nothing on empty input

### ISSUE THREAD

**Issue by milahu** [uktrade/stream-zip#116]
currently empty input returns 22 bytes

```py
from stream_zip import stream_zip
assert (
  b"".join(list(stream_zip([]))).hex() ==
  "504b0506000000000000000000000000000000000000"
)
```

this is not useful for my application, and i would prefer an empty output

```py
from stream_zip import stream_zip
assert list(stream_zip([])) == []
```

**Comment by michalc** [comment]
Hi @milahu,

This is pretty much by design - so it's still a valid ZIP file. e.g. from https://en.wikipedia.org/wiki/ZIP_(file_format)

> The minimum size of a .ZIP file is 22 bytes

(Standard caveat - can't trust Wikipedia in general, but in this case I argue it's right)

Say for example if you try to open such a 22-bytes file in MacOS you get this message, which is pretty accurate and I guess I would guess helpful in many cases:

<img width="490" alt="Screenshot 2024-03-10 at 13 39 53" src="https://github.com/uktrade/stream-zip/assets/13877/97b738b0-afdf-481a-b6f7-98318a971627">

But if you try to open a zero length file:

<img width="490" alt="Screenshot 2024-03-10 at 13 40 55" src="https://github.com/uktrade/stream-zip/assets/13877/c72304de-7cda-439d-8a03-4fa7939686ca">

I think it's ever so slightly less helpful in many cases...

... although with the possible exception of your case. Do you have more details on why you would like 0 bytes instead of the more regular 22 bytes that would make it a valid ZIP file?

**Comment by michalc** [comment]
In any case, you should be able to construct your own wrapper function that essentially buffers the first 22 bytes of the ZIP, so if there is _only_ 22 bytes of the ZIP, it yields nothing, and behaves exactly like `stream_zip` otherwise.

For example:

```python
def stream_zip_empty_if_no_member_files(member_files, **kwargs):
    num_bytes = 0
    initial_cache = []

    for chunk in stream_zip(member_files, **kwargs):
        num_bytes += len(chunk)
        if num_bytes <= 22:
            initial_cache.append(chunk)
        else:
            if initial_cache:
                yield from initial_cache
                initial_cache = []
            yield chunk
```

(This handles the case of `member_files` being an a general iterable without a known length, but also setting `chunk_size` to something small as well)

**Comment by milahu** [comment]
> wrapper function that essentially buffers the first 22 bytes of the ZIP

im doing that already as a workaround in [get-subs.py](https://github.com/milahu/opensubtitles-scraper/blob/45d0284dfc0ad1cc99801767df29a96d455daee2/get-subs.py#L277) 

> Do you have more details on why you would like 0 bytes

this is a cgi script on an http server, and if the archive is empty
i want to return an http 404 error page with content-type text/plain

i suggest to make this optional

**Comment by michalc** [comment]
> this is a cgi script on an http server, and if the archive is empty
i want to return an http 404 error page with content-type text/plain
basically, this is a search engine that returns results as zip file

Understood, thanks

> i suggest to make this optional

But I think I'm going to say no to this. You have a workaround already that doesn't need code in stream-zip. Or by using something like the one above in this thread, you can make it a touch more "standalone" without intertwining zip file and web server logic.

Or even, one other way has crossed my mind. Instead of doing something at the zip level, do something at the member file level a bit earlier, detecting if you have at least one member file up-front:

```python
member_files = ... whatever it is now

def with_at_least_one(iterable):
    it = iter(iterable)
    at_least_one = True

    try:
        value = next(it)
    except StopIteration:
        at_least_one = False

    def new_iterable():
        nonlocal value  # Makes it more likely to clear the memory from the first "value"

        if not at_least_one:
            return

        yield value

        while True:
            try:
                value = next(it)
            except StopIteration:
                break
            yield value

    return new_iterable(), at_least_one
```
Used like:
```python
member_files, at_least_one = with_at_least_one(member_files)
```
So then you nicely can have
```python
if at_least_one:
    # Send a 200 and construct the ZIP
    for chunk in stream_zip(member_files):
        ...
    
else:
   # Send a 404 
```
And it's still fully stream-y in terms of the member files.

**Comment by milahu** [comment]
> You have a workaround already that doesn't need code in stream-zip.

yeah, "has workaround" is an argument too ^^

nevermind, thanks : )
