### ISSUE TITLE
Ability to configure chunk size

### ISSUE THREAD

**Issue by alec-bell** [uktrade/stream-zip#19]
Thanks so much for building this package. It is incredibly useful.

One feature that would make this more powerful, in my opinion, is to be able to configure the chunk size you receive from the generator. I noticed that it provides chunks of 65,536 bytes.

The reason is that this tool is particularly useful when uploading zip files by way of multipart uploads. I am personally working on a project that needs to upload upwards of terabyte-sized directories to S3, and I generate URLs for each gigabyte that will be uploaded. I had to concatenate the chunks together until they were a gigabyte before I could run the upload on each multipart URL. This wasn't challenging, but I think it'd be a nice interface improvement.

Maybe there's something I missed in the documentation that does allow for something like this. Please keep me posted.

Thanks again!

**Comment by michalc** [comment]
Ah thanks for the thanks - very pleased it's useful :-)

On the chunk size, it's not documented, but there is the [`chunk_size` parameter to stream_unzip](https://github.com/uktrade/stream-zip/blob/main/stream_zip.py#L10). It's not meant to be a private API or anything like that, it's just that the documentation hasn't been gotten around to being written for it.

However, it is a sort of "general" chunk size for all stream_unzip processing - used for _incoming_ data as well. For example, it gathers `chunk_size` data before doing any decompression. That may or may not be what you want in this case - e.g. it might end up using too much memory?

(Also, just for posterity since it sounds very close to what you're doing anyway, I always imagined that something like https://github.com/uktrade/stream-zip#file-like-object could be used to convert the iterable output of stream_unzip (of any chunk size) into a file-like object, and then [boto3's uploadfileobj](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.upload_fileobj) used which can control the multipart object size)

**Comment by michalc** [comment]
I've now added some [documentation on how to use boto3 to upload large zip files to S3](https://github.com/uktrade/stream-zip#file-like-object), and some [documentation on the existing chunk_size parameter](https://github.com/uktrade/stream-zip#custom-chunk-size).

For now at least, I think this is enough. Potentially we could incorporate the `to_file_like_obj` function into stream_zip itself, but I lean a bit to keeping it as more as a recipe in order to keep stream_zip more minimal

**Comment by alec-bell** [comment]
Thanks @michalc for the quick responses! I didn't realize that parameter was available, but it's exactly what I need. The README looks great.
