### ISSUE TITLE
Calculate final zip size before starting

### ISSUE THREAD

**Issue by TaToTanWeb** [uktrade/stream-zip#21]
Hi, first of all thanks for the great work!
Is there a way to know the size of the compressed before starting? An example usecase could be the "Content-Length" header in servers, but I'd need it in some other scenarios too (even no-compression would be okay in this case).
Thanks :)

**Comment by michalc** [comment]
I can very much understand wanting to do this (I have wanted to myself) but I don't think there's a way to predict ahead of time exactly how big something will be compressed. There only way to find out is to actually compress it.

It is probably possible for no compression though. The length of the final file would be predictable based on the length of the input files and the file names. I'll have a think and see if I can come up with the formulas.

Can I check the exact use cases / scenarios though? You never know, there might be work arounds...

**Comment by michalc** [comment]
So here's a first pass at a function that works out the "boilerplate" length of the stuff in the ZIP file for those that _only_ contain uncompressed member files. 

```python
def get_boilerplate_length(unzipped_files):
    files = list(unzipped_files)

    is_zip_64 = any(file_type == NO_COMPRESSION_64 for _, _, _, file_type, _ in files)
    base = 98 if is_zip_64 else 22
    return base + sum(
        (len(name.encode('utf-8')) * 2) + (76 if file_type == NO_COMPRESSION_32 else 124)
        for name, _, _, file_type, _ in files
    )
```
You can use it by passing an iterable in the same structure as the one you would pass to `stream_unzip`, e.g.
```
boilerplate_length = get_boilerplate_length(unzipped_files())
```
The "boilerplate" is everything _except_ the actual length of the member files themselves. To find the total length of the zip file, you would have to add all the lengths of member files to the return value of `get_boilerplate_length`

Also just to re-iterate the warning from the README - files that are not compressed are buffered in memory, and so are not truly "streaming"

Also, I wouldn't really depend on the above code to work on future versions of stream-zip. ZIP files can container extra metadata, and potentially some could be added in a future version.

**Comment by TaToTanWeb** [comment]
Thank you so much for the reply!

**Comment by pR0Ps** [comment]
I found this when searching for something unrelated, but coincidentally, I may be able to help.

@TaToTanWeb: You can reliably calculate the final size of a streamed zip file, but only when not compressing the data and when you know the size of the data to add up-front. For adding files this is easy since you can just get the size of the file. For adding data from an iterator of some kind (like downloading data from an HTTP connection) you'll either need to also provide the total size of the data (if it's known), or buffer it all into memory to calculate the length first.

If these restrictions are an acceptable trade-off for your use-case, I'd recommend checking out a project I maintain called [`zipstream-ng`](https://github.com/pR0Ps/zipstream-ng) to see if it works for you. An express goal of the project is to be able to reliably calculate the length the streamed zip will be, specifically for setting a `Content-Length` header.

@michalc: If you wanted to implement size calculation into this project feel free to have a look at [my implementation of it](https://github.com/pR0Ps/zipstream-ng/blob/ddc807ea8050b77baef439c7116a86dbfafeebc8/zipstream/ng.py#L992). It's licensed under the LGPL so you wouldn't be able to copy/paste it into this MIT-licensed project, but the comments alone should hopefully give a pretty good idea of how to do it.
