### ISSUE TITLE
Package on PyPI

### ISSUE THREAD

**Issue by frafra** [uktrade/stream-zip#22]
Hi!
Thank you for this useful library. I was wondering if there is any plan to publish it to PyPI.

**Comment by michalc** [comment]
Hi,

Yes it's already done: https://pypi.org/project/stream-zip/

**Comment by frafra** [comment]
My bad! Might I suggest adding it to `README.md`? A badge could be used: ![PyPI](https://img.shields.io/pypi/v/stream-zip)

**Comment by michalc** [comment]
Ah thanks for the suggestion. Now done

**Comment by michalc** [comment]
Actually I am curious, can I ask your use case for stream-zip?

**Comment by frafra** [comment]
Sure! 

I maintain a data portal, and some datasets contains a lot of files; it is much easier to fetch the whole dataset as a ZIP file, but creating the archive as a regular file when the user requests it, can require some time, so the user would stand still and see nothing. It is way better to have the download start right away. This also avoids hitting some spurious timeouts or having to implement a queue with some kind of notification mechanism. There is no risk to think about files, lock, cleaning things up or worry about memory usage.

The second goal I am aiming for, is to generate a custom ZIP file, according to a specific format, called DarwinCore Archive, quite popular among ecologists. I will develop an additional function, which merges some files and generates a DarwinCore metadata file on the fly, based on some API responses of the data portal I was mentioning. This will provide an additional compatibility layer.

Here is the software: https://github.com/COATnor/coat-bulk-download

**Comment by michalc** [comment]
> I maintain a data portal, and some datasets contains a lot of files; it is much easier to fetch the whole dataset as a ZIP file, but creating the archive as a regular file when the user requests it,

Ah essentially the typical use case for this I think

> The second goal I am aiming for, is to generate a custom ZIP file, according to a specific format, called DarwinCore Archive, quite popular among ecologists

Ah if you're curious/if it's helpful, https://github.com/uktrade/stream-write-ods is a library to make ZIP-based OpenDocument Spreadsheet files in a streaming way built on stream-zip. Also to read such files https://github.com/uktrade/stream-read-ods built on stream-unzip

> It looks much better to rely on stream-unzip, since my code requires libarchive-c,

Ah I didn't even consider/really know about libarchive-c. From briefly testing/nosing around, it has a lot of overlap in terms of behaviour with stream-zip/stream-unzip. (Although I don't think it supports uncompressing Deflate64 ZIP files, and so far also seems to show an error on ZIPs created by Java with a member that when uncompressed is exactly 4294967295 bytes long).

(I'm now mostly just talking to myself, but in case you/someone is interested...) One thing that I think libarchive supports that stream-unzip doesn't, is streaming decompression of ZIPs with non-compressed members that use a data descriptor. This case is particularly tricky since the size of the member file is not stated before the file in the stream, so you can't for sure know when you get to the end of the member data in the stream. It looks like libarchive [peeks into the data](https://github.com/libarchive/libarchive/blob/master/libarchive/archive_read_support_format_zip.c#L1352), and if it finds something that looks like the correct data descriptor (which usually includes the bytes `PK\x07\x08`, and a CRC32 of the preceding data), it treats that point as the end of the member file. So there is a risk that it would match too early in files that just happen to have data that look like the right descriptor. Maybe the risk of this happening accidentally is astronomically small though...

**Comment by michalc** [comment]
If you’re curious, I have reported the libarchive issue at https://github.com/libarchive/libarchive/issues/1834
